name: mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - pre-commit
  - sphinx
  - sphinx-autoapi
  - sphinx-rtd-theme
  - m2r2
  - mistune
  - bandit
  - pip-audit
  - nbconvert
  - ipywidgets
  - pandas-profiling
  - seaborn
  - plotly
  - plotly_express
  - flask
  - scikit-learn
  - xgboost
  - shap
  - awscli
  - boto3
  - awswrangler 
  - ipykernel

